# Generated by Django 2.1.7 on 2019-05-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saunterer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='incubator',
            new_name='booking_form',
        ),
    ]
