# Generated by Django 2.1.7 on 2019-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('img_1', models.FileField(upload_to='')),
                ('img_2', models.FileField(upload_to='')),
            ],
        ),
    ]
