# Generated by Django 2.1.7 on 2019-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='footer',
            field=models.TextField(default='Summarize/Conclude'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_caption',
            field=models.TextField(default='Image Caption'),
        ),
    ]
